version: '3'
services:
  xhuicloud-mysql:
    build:
      context: ./doc/db
    restart: always
    container_name: xhuicloud-mysql
    image: xhuicloud-mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password

  xhuicloud-mq:
    image: rabbitmq:3-management
    container_name: xhuicloud-mq
    restart: always
    hostname: xhuicloud-mq
    volumes:
      - ./doc/mq/rabbitmq_delayed_message_exchange-3.9.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.9.0.ez
      - ./doc/mq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_DEFAULT_VHOST=xhuicloud

  xhuicloud-redis:
    container_name: xhuicloud-redis
    image: redis:6.2.6
    command: redis-server --requirepass root
    restart: always
    ports:
      - 6379:6379

  xhuicloud-zk:
    image: zookeeper:3.4.11
    restart: always
    container_name: xhuicloud-zk
    ports:
      - 2181:2181

  xhuicloud-register:
    build:
      context: ./XHuiCloud-business/XHuiCloud-register
    restart: always
    container_name: xhuicloud-register
    image: xhuicloud-register
    depends_on:
      - xhuicloud-mysql
    ports:
      - 13000:13000

  xhuicloud-gateway:
    build:
      context: ./XHuiCloud-business/XHuiCloud-gateway
    restart: always
    container_name: xhuicloud-gateway
    image: xhuicloud-gateway
    ports:
      - 15000:15000

  xhuicloud-auth:
    build:
      context: ./XHuiCloud-auth
    restart: always
    container_name: xhuicloud-auth
    image: xhuicloud-auth

  xhuicloud-upms:
    build:
      context: ./XHuiCloud-upms/XHuiCloud-upms-service
    restart: always
    container_name: xhuicloud-upms
    image: xhuicloud-upms

  xhuicloud-logs:
    build:
      context: ./XHuiCloud-business/XHuiCloud-logs/XHuiCloud-logs-service
    restart: always
    container_name: xhuicloud-logs
    image: xhuicloud-logs

  xhuicloud-pay:
    build:
      context: ./XHuiCloud-business/XHuiCloud-pay/XHuiCloud-pay-service
    restart: always
    container_name: xhuicloud-pay
    image: xhuicloud-pay

  xhuicloud-push:
    build:
      context: ./XHuiCloud-business/XHuiCloud-push/XHuiCloud-push-service
    restart: always
    container_name: xhuicloud-push
    image: xhuicloud-push

  xhuicloud-xxl-admin:
    build:
      context: ./XHuiCloud-business/XHuiCloud-xxl-admin/XHuiCloud-xxl-admin-service
    restart: always
    container_name: xhuicloud-xxl-admin
    image: xhuicloud-xxl-admin

  xhuicloud-job:
    build:
      context: ./XHuiCloud-business/XHuiCloud-job/XHuiCloud-job-service
    restart: always
    container_name: xhuicloud-job
    image: xhuicloud-job

  xhuicloud-seata:
    build:
      context: ./XHuiCloud-business/XHuiCloud-seata
    restart: always
    container_name: xhuicloud-seata
    image: xhuicloud-seata

  xhuicloud-generator:
    build:
      context: ./XHuiCloud-business/XHuiCloud-generator
    restart: always
    container_name: xhuicloud-generator
    image: xhuicloud-generator

