version: '2'
services:
  xhuicloud-mysql:
    build:
      context: doc/db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: xhuicloud-mysql
    image: xhuicloud-mysql
    ports:
      - 3306:3306
    volumes:
      - ./xhuicloud-mysql:/var/lib/mysql
    command: --lower_case_table_names=1

  xhuicloud-redis:
    container_name: xhuicloud-redis
    image: redis:5.0.7
    restart: always
    ports:
      - 6379:6379

  xhuicloud-zk:
    image: zookeeper:3.4.11
    restart: always
    container_name: xhuicloud-zk
    ports:
      - 2181:2181

  xhuicloud-register:
    build:
      context: ./FDP-management-business/FDP-register
    environment:
      - REDIS_HOST=xhuicloud-redis
      - MYSQL_HOST=xhuicloud-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
    container_name: xhuicloud-register
    image: xhuicloud-register
    ports:
      - 13000:13000

  xhuicloud-gateway:
    build:
      context: ./FDP-management-business/XHuiCloud-gateway
    environment:
      - REDIS_HOST=xhuicloud-redis
      - NACOS_HOST=xhuicloud-register
      - NACOS_PORT=13000
    restart: always
    container_name: xhuicloud-gateway
    image: xhuicloud-gateway
    ports:
      - 15000:15000

  xhuicloud-auth:
    build:
      context: ./FDP-auth
    environment:
      - REDIS_HOST=xhuicloud-redis
      - NACOS_HOST=xhuicloud-register
      - NACOS_PORT=13000
      - MYSQL_HOST=xhuicloud-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
    container_name: xhuicloud-auth
    image: xhuicloud-auth

  xhuicloud-upmm:
    build:
      context: ./FDP-upmm/FDP-upmm-business
    environment:
      - REDIS_HOST=xhuicloud-redis
      - NACOS_HOST=xhuicloud-register
      - NACOS_PORT=13000
      - MYSQL_HOST=xhuicloud-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
    container_name: xhuicloud-upmm
    image: xhuicloud-upmm

  xhuicloud-logs:
    build:
      context: ./FDP-management-business/FDP-logs/FDP-logs-business
    environment:
      - NACOS_HOST=xhuicloud-register
      - NACOS_PORT=13000
      - MYSQL_HOST=xhuicloud-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
    container_name: xhuicloud-logs
    image: xhuicloud-logs

  xhuicloud-pay:
    build:
      context: ./FDP-management-business/FDP-pay/FDP-pay-business
    environment:
      - ZK_HOST=xhuicloud-zk
      - ZK_PORT=2181
      - NACOS_HOST=xhuicloud-register
      - NACOS_PORT=13000
      - MYSQL_HOST=xhuicloud-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
    container_name: xhuicloud-pay
    image: xhuicloud-pay

  xhuicloud-gen:
    build:
      context: ./FDP-management-business/FDP-generator
    environment:
      - NACOS_HOST=xhuicloud-register
      - NACOS_PORT=13000
      - MYSQL_HOST=xhuicloud-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
    container_name: xhuicloud-gen
    image: xhuicloud-gen
