server:
  port: 15000

nacos:
  address: 127.0.0.1:13000
spring:
  application:
    name: FDP-gateway
  cloud:
    nacos:
      discovery:
        #nacos 地址
        server-addr: ${nacos.address}
    sentinel:
      transport:
        # sentinel 地址
        dashboard: localhost:14000
        #监控此服务端口
        port: ${server.port}
    gateway:
      discovery:
        locator:
          #通过nacos找到注册的其他微服务 调用方式 http://Gateway ip:Gateway port/目标服务名/ +uri
          enabled: true


